examples/qat/post.py
=> Fix bug in post-quantization sample

tinynn/graph/quantization/quantizer.py
Skip log_softmax with this commit.
=> [quantizer] skip log_softmax

.github/workflows/unit-test.yml, examples/converter/convert_and_compare.py, examples/converter/convert_from_json.py, tests/converter_op_test.py, tests/converter_optimizer_test.py, tests/converter_test.py, tinynn/converter/base.py, tinynn/converter/operators/graph.py, tinynn/converter/operators/optimize.py, tinynn/util/converter_util.py
This reverts commit f6bc859405da2c9bd7528acbffe5692d67e52e33.
=> Revert "Revert "[converter] support output_transpose""

.pre-commit-config.yaml, tests/converter_op_test.py, tests/converter_optimizer_test.py, tinynn/converter/operators/optimize.py
1. Adding post-fusion strategy of conv2d-gather sequentice
2. Adding test cases for optimizer & op
=> [converter] add post-fusion strategy of conv2d-gather sequences & test-cases

tinynn/graph/quantization/quantizer.py
=> [quantizer] add PTQ-only fusion rules

tests/converter_op_test.py, tinynn/converter/operators/optimize.py
Fix the quantization issue of conv2d-gather, as discussed in DingTalk
=> [converter] fix quantization issue of post-fusion strategy of conv2d-gather sequences & test-cases

tinynn/converter/base.py, tinynn/converter/operators/__init__.py, tinynn/converter/operators/half_quantizer.py, tinynn/converter/operators/tflite/base.py
=> [converter] float16 quantization

docs/FAQ.md, docs/FAQ_zh-CN.md, tinynn/graph/_utils.py, tinynn/graph/configs/torch_tracking_modules.yml, tinynn/graph/quantization/quantizer.py, tinynn/graph/tracer.py
[tracer] add patch_torch_size
[quantizer] add extra_tracer_opts
=> [tracer&quantizer] add patch_torch_size & extra_tracer_opts

tinynn/graph/quantization/quantizer.py
1. Allow passing in layerwise_config through `config`
2. Make it possible to set default value for layerwise_config
3. Skip unrelated nodes including `shape`, `size`, `dtype` and `device`
4. Enable consecutive dq-q removal for branch nodes
=> [quantizer] improve layerwise_config

docs/op_matrix.md, tinynn/converter/operators/torch/__init__.py, tinynn/converter/operators/torch/prim.py
=> [converter] add prim::DictConstruct

tests/converter_optimizer_test.py, tinynn/converter/operators/optimize.py, tinynn/converter/operators/tflite/transformable.py
have some difficulties on writing tests though merging convtranspose2d & relu successfully(float)
=> update fused_activation option

tinynn/converter/operators/optimize.py
=> [converter] fix elementwise pass for pack ops

tinynn/converter/operators/optimize.py
Refines for the model provided in #252
=> [converter] refine reshape transpose pass

tinynn/converter/operators/torch/aten.py
=> [converter] support elem logic for aten::{max,min}

docs/op_matrix.md, tests/converter_op_test.py, tinynn/converter/operators/torch/aten.py
Fixes https://github.com/alibaba/TinyNeuralNetwork/issues/282
=> [converter] support aten::index for multi dims

docs/op_matrix.md, tests/converter_op_test.py, tinynn/converter/operators/torch/__init__.py, tinynn/converter/operators/torch/aten.py
Fixes https://github.com/alibaba/TinyNeuralNetwork/issues/287
=> [converter] add aten::repeat_interleave

tinynn/graph/quantization/quantizer.py
=> [quantizer] fix check_node_quantized for is_fusable

tests/converter_op_test.py, tinynn/converter/operators/torch/aten.py, tinynn/converter/operators/torch/base.py
Fixes https://github.com/alibaba/TinyNeuralNetwork/issues/330
=> [converter] fix tensor check constraint

examples/quantization/specific/vit/vit_post.py
Fixes https://github.com/alibaba/TinyNeuralNetwork/issues/343
=> [examples] fix vit ptq

tinynn/graph/quantization/quantizer.py
=> [tracer] apply move_idx=True for graph.insert_between

tinynn/graph/quantization/quantizer.py
Fixes https://github.com/alibaba/TinyNeuralNetwork/issues/376.
=> [quantizer] fix logic for new_indices
